
//line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[500] =
    {   0,
        0,    0,   82,   80,   77,   76,   75,    3,   20,   80,
       15,   14,   12,   10,   17,   11,   13,   72,   16,    6,
        4,    8,   33,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   18,
       19,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   31,   32,    0,   71,    0,    0,
       70,    0,    0,    0,    0,   72,   74,   73,   73,    7,
        5,    9,   74,   74,   74,   74,   31,   74,   74,   74,
       27,   74,   74,   21,   74,   74,   74,    0,   74,   32,

       74,    0,   74,   21,   21,   74,   74,   29,   74,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       31,   73,   73,   73,   73,   73,   27,   73,   73,   73,
       73,   73,   21,   73,   73,   73,   73,   73,   73,   73,
       73,   32,    1,   73,   73,   73,   73,   73,   73,   73,
       21,   73,   73,   73,   29,   73,   73,   73,   73,    2,
        0,   71,    0,    0,   70,    0,    0,    0,    0,   78,
       72,   74,   74,   35,   36,   74,   74,   24,   74,   74,
       24,   30,   74,   74,   74,   74,   74,    0,   74,   74,
       74,    0,   74,    0,   74,   74,   74,   74,   73,   73,

       73,   73,   73,   73,   73,   73,   73,   35,   73,   36,
       73,   44,   73,   73,   24,   73,   73,   73,   73,   24,
       30,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   66,   73,   73,   73,   73,
       73,   73,   73,    0,   73,   73,   73,   73,   73,   59,
       73,   73,   73,   79,   74,   22,   74,   74,   26,   74,
       37,    0,   74,   74,   74,   74,   34,   74,    0,   74,
       74,   23,    0,    0,   74,   25,   74,   73,   73,   73,
       73,   73,   22,   73,   73,   73,   73,   73,   73,   73,
       73,   26,   73,   73,   73,   37,    0,   73,   73,   73,

       73,   73,   73,   73,   73,   34,   73,   73,   73,   73,
       73,   73,   73,   23,   65,   73,   73,   73,    0,   49,
       73,   73,   25,   73,   73,   73,   74,   74,   74,    0,
       74,   74,   74,    0,   74,   33,   74,    0,    0,   74,
       28,   50,   73,   73,   39,   73,   73,   73,   60,   73,
       73,   73,   73,   73,   73,   73,    0,    0,    0,   73,
       73,   73,   73,   73,   73,   45,   73,   73,   73,   73,
       69,   33,   73,   73,   73,   55,    0,   73,   41,   73,
       73,   28,   74,   74,    0,   74,   74,   22,   74,   74,
        0,   27,   74,   73,   35,   56,   51,   73,   73,   73,

       73,   73,   73,   73,   48,    0,    0,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       53,   73,   74,   74,   32,   74,   74,   74,   74,    0,
       74,   73,   46,   73,   73,   73,   73,   73,   73,    0,
        0,   73,   67,   73,   64,   73,   73,   42,   73,   52,
       73,   73,   73,   73,   38,   74,   74,   74,    0,   73,
       73,   73,   73,   58,   40,    0,    0,   73,   43,   57,
       73,   62,   68,   36,   74,    0,   73,   54,   47,   36,
        0,   73,   74,    0,   61,    0,   73,   74,    0,    0,
       73,   74,    0,   63,   73,   23,   23,   23,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,   21,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   28,   28,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   28,   41,   42,   28,   43,
       44,   45,   46,    1,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,   73,   74,    1,   75,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    2,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1
    } ;

static const flex_int16_t yy_base[508] =
    {   0,
        0,    0,  633,  634,  634,  634,  634,   71,  634,   70,
      634,  634,  634,  634,  634,  634,   68,  103,  634,   60,
      634,  613,  634,    0,  597,   59,   58,   54,   52,  608,
       61,   63,  599,  603,   58,  587,   68,   71,  597,  634,
      634,   85,   53,   42,  129,   56,  123,  127,   41,  577,
       60,    0,   55,  141,  136,  148,  556,  571,  151,  149,
      556,  154,  566,  548,  634,  634,  174,  634,  175,  141,
      634,  202,  609,  615,  601,    0,    0,  133,    0,  634,
      634,  634,  579,  584,  576,  176,    0,  575,  183,  582,
      578,  573,  188,    0,  574,  582,  585,  558,  579,    0,

      187,  542,  573,  202,  634,  565,  575,    0,  570,  534,
      531,  158,  531,  537,  530,  529,  162,  532,  177,  532,
        0,  173,  179,  535,  542,  533,  527,  522,  525,  537,
      536,  182,    0,  520,  516,  529,  519,  531,  517,  525,
      510,    0,    0,  507,  511,  178,  507,  516,  182,  512,
      220,  508,  173,  517,    0,  516,  517,  505,  509,    0,
      232,  237,  247,  234,  238,  250,  554,  241,  560,  634,
      546,  524,  529,    0,  529,  533,  531,    0,  522,  516,
      241,    0,  528,  514,  515,  514,  518,  489,  515,  514,
      522,  495,  505,  516,  508,  509,  507,  508,  482,  469,

      471,  473,  484,  474,  467,  481,  464,    0,  191,  473,
      477,    0,  467,  474,    0,  463,  460,  464,  455,  246,
        0,  471,  467,  454,  466,  450,  451,  463,  449,  461,
      452,  445,  449,  442,  442,    0,  446,  456,  450,  437,
      447,  440,  445,  447,  437,  435,  437,  429,  434,    0,
      438,  426,  433,  634,  469,    0,  458,  463,    0,  455,
        0,  458,  455,  448,  462,  453,    0,  460,  433,  441,
      440,  452,  425,  446,  445,    0,  448,  408,  424,  423,
      409,  421,    0,  420,  399,  414,  409,  412,  403,  410,
      405,    0,  399,  391,  390,    0,  206,  398,  400,  399,

      403,  388,  404,  395,  385,    0,  401,  400,  399,  379,
      380,  396,  376,  390,    0,  375,  375,  374,  382,    0,
      381,  374,    0,  387,  386,  381,  395,  409,  406,  407,
      398,  395,  389,  360,  387,    0,  398,  371,  388,  387,
        0,    0,  360,  353,    0,  352,  351,  356,    0,  353,
      348,  364,  350,  360,  357,  360,  359,  354,  349,  348,
      341,  352,  353,  340,  332,    0,  333,  340,  331,  347,
        0,    0,  343,  326,  331,    0,  330,  329,    0,  324,
      327,    0,  356,  360,  342,  341,  353,  634,  360,  351,
      324,  634,  357,  322,    0,    0,    0,  315,  308,  308,

      315,  325,  320,  304,    0,  212,  316,  296,  307,  305,
      301,  309,  316,  311,  314,  296,  304,  294,  310,  309,
        0,  308,  329,  316,  634,  331,  315,  313,  318,  289,
      311,  274,    0,  298,  289,  292,  278,  276,  293,  288,
      283,  290,    0,  271,    0,  271,  270,    0,  268,    0,
      273,  270,  266,  265,    0,  291,  291,  297,  270,  277,
      242,  228,  225,    0,    0,  225,  223,  223,    0,    0,
      231,    0,    0,    0,  260,  232,  215,    0,    0,    0,
      211,  224,  242,  213,    0,  208,  209,  230,  201,  205,
      199,  231,  202,  634,   29,    0,  634,    0,  634,  295,

      299,  302,  304,  308,  312,  316,  320
    } ;

static const flex_int16_t yy_def[508] =
    {   0,
      499,    1,  499,  499,  499,  499,  499,  500,  499,  501,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  499,
      499,   18,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  499,  499,  500,  499,  504,  501,
      499,  505,  506,  507,  499,   18,  502,   18,  503,  499,
      499,  499,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  499,  502,  502,

      502,  499,  502,  502,  499,  502,  502,  502,  502,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      500,  500,  504,  501,  501,  505,  506,  506,  507,  499,
      499,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  499,  502,  502,
      502,  499,  502,  499,  502,  502,  502,  502,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  499,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  499,  502,  502,  502,  502,  502,  502,
      502,  499,  502,  502,  502,  502,  502,  502,  499,  502,
      502,  502,  499,  499,  502,  502,  502,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  499,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  499,  503,
      503,  503,  503,  503,  503,  503,  502,  502,  502,  499,
      502,  502,  502,  499,  502,  502,  502,  499,  499,  502,
      502,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  499,  499,  499,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  499,  503,  503,  503,
      503,  503,  502,  502,  499,  502,  502,  499,  502,  502,
      499,  499,  502,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  499,  499,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  502,  502,  499,  502,  502,  502,  502,  499,
      502,  503,  503,  503,  503,  503,  503,  503,  503,  499,
      499,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  502,  502,  502,  499,  503,
      503,  503,  503,  503,  503,  499,  499,  503,  503,  503,
      503,  503,  503,  502,  502,  499,  503,  503,  503,  503,
      499,  503,  502,  499,  503,  499,  503,  502,  499,  499,
      503,  502,  499,  499,  503,  502,  499,  503,    0,  499,

      499,  499,  499,  499,  499,  499,  499
    } ;

static const flex_int16_t yy_nxt[710] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,    4,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   24,   30,   31,
       32,   33,   24,   34,   35,   36,   24,   37,   38,   24,
       39,   24,   24,   40,    4,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   52,   53,   54,
       52,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       52,   64,   52,   65,   66,   68,   71,   73,   80,   81,
       84,   91,   74,   86,   88,   92,   89,   94,   96,   85,
      498,   87,   95,   97,  101,   90,  106,  104,  499,  107,

       78,  110,  111,  112,  108,  130,  136,  119,  131,  113,
      137,  120,  133,  138,   72,   69,   75,  121,   76,  134,
      135,   98,  102,  105,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,  499,   71,   78,   78,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,  114,   67,   68,  162,
      115,  122,  127,  123,  116,   72,  142,  117,  128,  124,
      118,  125,  139,  126,  129,  144,  140,  143,  150,  175,

      153,  157,  141,  154,   70,  158,  151,  178,  165,  145,
      155,  183,  146,  176,  194,  147,  190,  152,   69,  163,
      191,  179,  201,  207,  202,  184,  210,  208,  213,  215,
       87,  225,  244,  237,  195,  241,   68,  247,  214,  238,
       71,   68,  211,  248,   71,  216,  166,  226,  242,   67,
      168,  162,   70,  262,  121,  254,  165,  287,  297,  288,
      357,  440,  263,  497,  496,  495,  494,  493,  492,  491,
      358,  359,  490,  489,  488,  487,   69,  486,   72,  485,
      245,   69,   72,  484,  425,  483,  482,  296,  481,  425,
      480,  163,  479,  298,  166,   67,   67,   67,   67,   70,

       70,   70,   70,   77,   77,   79,  478,   79,  161,  161,
      161,  161,  164,  164,  164,  164,  167,  167,  167,  167,
      169,  169,  169,  169,  477,  476,  475,  261,  474,  296,
      473,  472,  471,  382,  470,  372,  469,  468,  467,  466,
      465,  323,  464,  463,  462,  461,  460,  261,  459,  458,
      341,  336,  457,  276,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      439,  438,  437,  436,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      392,  419,  418,  417,  416,  415,  414,  283,  413,  412,

      411,  410,  409,  408,  392,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  388,  256,  387,  386,  385,  384,
      383,  174,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  155,  121,  363,  362,  361,  360,  356,  355,  354,
      353,  221,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  108,   87,  331,  330,  329,  182,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  292,  319,

      318,  317,  316,  296,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  296,  295,  294,  293,  292,  291,  290,  289,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  259,  274,  261,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  261,  260,  259,  258,  257,  256,
      255,  171,  170,  168,  253,  252,  251,  250,  249,  246,
      243,  240,  239,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  224,  223,  222,  221,  220,  219,  218,
      217,  212,  209,  206,  205,  204,  203,  200,  199,  198,

      197,  196,  193,  192,  189,  188,  187,  186,  185,  182,
      181,  180,  177,  174,  173,  172,  171,  170,  168,  160,
      159,  156,  149,  148,  132,  109,  103,  100,   99,   93,
       83,   82,  499,    3,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499
    } ;

static const flex_int16_t yy_chk[710] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,   10,   17,   20,   20,
       26,   29,   17,   27,   28,   29,   28,   31,   32,   26,
      495,   27,   31,   32,   35,   28,   38,   37,   42,   38,

       42,   43,   43,   44,   38,   49,   53,   46,   49,   44,
       53,   46,   51,   53,   10,    8,   18,   46,   18,   51,
       51,   32,   35,   37,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   78,   70,   78,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   45,   69,   67,   69,
       45,   47,   48,   47,   45,   70,   55,   45,   48,   47,
       45,   47,   54,   47,   48,   56,   54,   55,   59,   86,

       60,   62,   54,   60,   72,   62,   59,   89,   72,   56,
       60,   93,   56,   86,  104,   56,  101,   59,   67,   69,
      101,   89,  112,  117,  112,   93,  119,  117,  122,  123,
       93,  132,  151,  146,  104,  149,  161,  153,  122,  146,
      164,  162,  119,  153,  165,  123,   72,  132,  149,  163,
      168,  163,  166,  181,  132,  168,  166,  209,  220,  209,
      297,  406,  181,  493,  492,  491,  490,  489,  488,  487,
      297,  297,  486,  484,  483,  482,  161,  481,  164,  477,
      151,  162,  165,  476,  406,  475,  471,  468,  467,  466,
      463,  163,  462,  220,  166,  500,  500,  500,  500,  501,

      501,  501,  501,  502,  502,  503,  461,  503,  504,  504,
      504,  504,  505,  505,  505,  505,  506,  506,  506,  506,
      507,  507,  507,  507,  460,  459,  458,  457,  456,  454,
      453,  452,  451,  449,  447,  446,  444,  442,  441,  440,
      439,  438,  437,  436,  435,  434,  432,  431,  430,  429,
      428,  427,  426,  424,  423,  422,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      404,  403,  402,  401,  400,  399,  398,  394,  393,  391,
      390,  389,  387,  386,  385,  384,  383,  381,  380,  378,
      377,  375,  374,  373,  370,  369,  368,  367,  365,  364,

      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  348,  347,  346,  344,  343,  340,
      339,  338,  337,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  322,  321,  319,  318,  317,
      316,  314,  313,  312,  311,  310,  309,  308,  307,  305,
      304,  303,  302,  301,  300,  299,  298,  295,  294,  293,
      291,  290,  289,  288,  287,  286,  285,  284,  282,  281,
      280,  279,  278,  277,  275,  274,  273,  272,  271,  270,
      269,  268,  266,  265,  264,  263,  262,  260,  258,  257,
      255,  253,  252,  251,  249,  248,  247,  246,  245,  244,

      243,  242,  241,  240,  239,  238,  237,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  219,  218,  217,  216,  214,  213,  211,  210,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  180,  179,  177,  176,  175,  173,
      172,  171,  169,  167,  159,  158,  157,  156,  154,  152,
      150,  148,  147,  145,  144,  141,  140,  139,  138,  137,
      136,  135,  134,  131,  130,  129,  128,  127,  126,  125,
      124,  120,  118,  116,  115,  114,  113,  111,  110,  109,

      107,  106,  103,  102,   99,   98,   97,   96,   95,   92,
       91,   90,   88,   85,   84,   83,   75,   74,   73,   64,
       63,   61,   58,   57,   50,   39,   36,   34,   33,   30,
       25,   22,    3,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
//line 1 "tokens.l"
/* IMPORTANTE:  no dejar espacios entre los | | | !!!!!1   github */
/* '[\x20-\x7D]{-}[\']+'  {   para LITERAL, en linux */
//line 5 "tokens.l"

#define linux
//#define windows

struct ast * nuevonodo(void);
void  cuentalineas(char * yytext);

#include "vars.h"


 

#include "nodo.h"
#include "stdio.h"

// #include "grammar_tab.h"

#ifdef windows
  //#include "grammar_tab.h"
#endif


#ifdef linux
 #include "grammar.tab.h"
#endif

extern YYSTYPE  yylval;
extern void  insAST(char * ) ;

 int contador = 0; 
 int  contadorvar = 0; 
 int contador_lineaInicial = 0;

extern int linenumber;
int lineaEjecucion = 0;
int lineaAnterior = 0;
int  LineaInicial[20] ;   //para anidar  IF, FOR, WHILE

int instala(x) 
int x;
{
   int i;
   strcpy (constantes[x],  yytext);
   i=0;
   while ( i < (strlen(yytext-2) ) ) { 
       constantes[x][i] = constantes[x][i+1]; i++;
    }
       	constantes[x][i-4] = '\0';
if(depurar)
	printf("CONSTANTE %d  --    %s\n", x, constantes[x]);  
   return x;
}

int variables_count = 0;
short myflag = 0;

char instalavar(x) 
int x;
{

   int i=0; myflag = 0;
   for (i=0; i<=contadorvar; i++) {
       if (!strcmp(yytext, array_variables[i].nombre)) {
                                contadorvar--;
                                variables_count++;
                                myflag = 1;
 		 return i ; }
           /* else printf("%d no igual...", i);   */
   };
   //strcpy (variables[x],  yytext);
   strcpy  (array_variables[x].nombre, yytext);
// if (depurar)
   //printf("VARIABLE %d  --    %s\n", x, variables[x]);
  // insAST(yytext) ;
/*   printf("%d  --    %s\n", x, variables[x]);  */
   return x;
}

lineaEjecucion2() {
    lineaAnterior = lineaEjecucion;
    lineaEjecucion = linenumber;
if (depurar)
    printf("Linea Ejecucion: %d\n", lineaEjecucion);
/*
    if (lineaEjecucion==12)
        pausar();
*/
}

//line 857 "lex.yy.c"
//line 858 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
//line 97 "tokens.l"

//line 1077 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 500 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 634 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
//line 98 "tokens.l"
{ return OR; }
	YY_BREAK
case 2:
YY_RULE_SETUP
//line 99 "tokens.l"
{ return AND; }
	YY_BREAK
case 3:
YY_RULE_SETUP
//line 100 "tokens.l"
{return DOBLECOMILLA; }
	YY_BREAK
case 4:
YY_RULE_SETUP
//line 101 "tokens.l"
{ return EQ; }
	YY_BREAK
case 5:
YY_RULE_SETUP
//line 102 "tokens.l"
{ return NE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
//line 103 "tokens.l"
{ return LT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
//line 104 "tokens.l"
{ return LE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
//line 105 "tokens.l"
{ return GT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
//line 106 "tokens.l"
{ return GE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
//line 107 "tokens.l"
{ return PLUS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
//line 108 "tokens.l"
{ return MINUS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
//line 109 "tokens.l"
{ return MULT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
//line 110 "tokens.l"
{ return DIVIDE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
//line 111 "tokens.l"
{ return RPAREN; }
	YY_BREAK
case 15:
YY_RULE_SETUP
//line 112 "tokens.l"
{ return LPAREN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
//line 113 "tokens.l"
{ return SEMICOLON; }
	YY_BREAK
case 17:
YY_RULE_SETUP
//line 114 "tokens.l"
{ return COMMA; }
	YY_BREAK
case 18:
YY_RULE_SETUP
//line 115 "tokens.l"
{ return '['; }
	YY_BREAK
case 19:
YY_RULE_SETUP
//line 116 "tokens.l"
{ return ']'; }
	YY_BREAK
case 20:
YY_RULE_SETUP
//line 117 "tokens.l"
{ return '#'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
//line 119 "tokens.l"
{LineaInicial [contador_lineaInicial] = linenumber; contador_lineaInicial++; return IF; }
	YY_BREAK
case 22:
YY_RULE_SETUP
//line 120 "tokens.l"
{lineaEjecucion2(); return LLAMAR ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
//line 121 "tokens.l"
{ return PROC ; }
	YY_BREAK
case 24:
YY_RULE_SETUP
//line 122 "tokens.l"
{ return END ; }
	YY_BREAK
case 25:
YY_RULE_SETUP
//line 123 "tokens.l"
{ return THEN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
//line 124 "tokens.l"
{ return ELSE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
//line 125 "tokens.l"
{ contador_lineaInicial--;  return FI; }
	YY_BREAK
case 28:
YY_RULE_SETUP
//line 126 "tokens.l"
{ LineaInicial [contador_lineaInicial] = linenumber; contador_lineaInicial++; return WHILE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
//line 127 "tokens.l"
{ return TO ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
//line 128 "tokens.l"
{LineaInicial [contador_lineaInicial] = linenumber; contador_lineaInicial++; return FOR ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
//line 129 "tokens.l"
{ return DO; }
	YY_BREAK
case 32:
YY_RULE_SETUP
//line 130 "tokens.l"
{contador_lineaInicial--; return OD; }
	YY_BREAK
case 33:
YY_RULE_SETUP
//line 131 "tokens.l"
{lineaEjecucion2(); return PRINT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
//line 132 "tokens.l"
{lineaEjecucion2(); return LEER; }
	YY_BREAK
case 35:
YY_RULE_SETUP
//line 133 "tokens.l"
{lineaEjecucion2(); return BORRAR ; }
	YY_BREAK
case 36:
YY_RULE_SETUP
//line 134 "tokens.l"
{lineaEjecucion2(); return DECIMALES; }
	YY_BREAK
case 37:
YY_RULE_SETUP
//line 135 "tokens.l"
{ return TERMINAR ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
//line 136 "tokens.l"
{lineaEjecucion2(); return VENTANA; }
	YY_BREAK
case 39:
YY_RULE_SETUP
//line 137 "tokens.l"
{lineaEjecucion2();  return BOTON; }
	YY_BREAK
case 40:
YY_RULE_SETUP
//line 138 "tokens.l"
{lineaEjecucion2();   return ETIQUETA; }
	YY_BREAK
case 41:
YY_RULE_SETUP
//line 139 "tokens.l"
{lineaEjecucion2(); return TEXTO; }
	YY_BREAK
case 42:
YY_RULE_SETUP
//line 140 "tokens.l"
{lineaEjecucion2(); return MENSAJE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
//line 141 "tokens.l"
{lineaEjecucion2(); return GRAFICOS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
//line 142 "tokens.l"
{lineaEjecucion2(); return DIM; }
	YY_BREAK
case 45:
YY_RULE_SETUP
//line 143 "tokens.l"
{lineaEjecucion2(); return LINEA; }
	YY_BREAK
case 46:
YY_RULE_SETUP
//line 144 "tokens.l"
{lineaEjecucion2(); return CIRCULO; }
	YY_BREAK
case 47:
YY_RULE_SETUP
//line 145 "tokens.l"
{lineaEjecucion2(); return CONVERTIR; }
	YY_BREAK
case 48:
YY_RULE_SETUP
//line 146 "tokens.l"
{lineaEjecucion2(); return EVALUAR; }
	YY_BREAK
case 49:
YY_RULE_SETUP
//line 147 "tokens.l"
{lineaEjecucion2();  return STOP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
//line 148 "tokens.l"
{ lineaEjecucion2();  return ABRIR; }
	YY_BREAK
case 51:
YY_RULE_SETUP
//line 149 "tokens.l"
{ lineaEjecucion2();  return CERRAR; }
	YY_BREAK
case 52:
YY_RULE_SETUP
//line 150 "tokens.l"
{lineaEjecucion2();    return MOSTRAR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
//line 151 "tokens.l"
{ lineaEjecucion2(); return VACIAR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
//line 152 "tokens.l"
{ lineaEjecucion2(); return CONTINUAR; }
	YY_BREAK
case 55:
YY_RULE_SETUP
//line 153 "tokens.l"
{ lineaEjecucion2(); return SALIR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
//line 154 "tokens.l"
{lineaEjecucion2(); return BUSCAR;}
	YY_BREAK
case 57:
YY_RULE_SETUP
//line 155 "tokens.l"
{lineaEjecucion2(); return INSERTAR;}
	YY_BREAK
case 58:
YY_RULE_SETUP
//line 156 "tokens.l"
{lineaEjecucion2(); return ELIMINAR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
//line 157 "tokens.l"
{lineaEjecucion2(); return USE_INDICE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
//line 158 "tokens.l"
{lineaEjecucion2(); return CLOSE_INDICE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
//line 159 "tokens.l"
{lineaEjecucion2(); return ACTUALIZAR; }
	YY_BREAK
case 62:
YY_RULE_SETUP
//line 160 "tokens.l"
{lineaEjecucion2(); return REGISTRO; }
	YY_BREAK
case 63:
YY_RULE_SETUP
//line 161 "tokens.l"
{lineaEjecucion2(); return FINREGISTRO; }
	YY_BREAK
case 64:
YY_RULE_SETUP
//line 162 "tokens.l"
{lineaEjecucion2(); return GUARDAR;}
	YY_BREAK
case 65:
YY_RULE_SETUP
//line 163 "tokens.l"
{lineaEjecucion2(); return PUSH;}
	YY_BREAK
case 66:
YY_RULE_SETUP
//line 164 "tokens.l"
{lineaEjecucion2(); return POP;}
	YY_BREAK
case 67:
YY_RULE_SETUP
//line 165 "tokens.l"
{lineaEjecucion2(); return FUNCION;}
	YY_BREAK
case 68:
YY_RULE_SETUP
//line 166 "tokens.l"
{lineaEjecucion2(); return RETORNAR;}
	YY_BREAK
case 69:
YY_RULE_SETUP
//line 167 "tokens.l"
{lineaEjecucion2(); return PAUSA; }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
//line 170 "tokens.l"
{  // '[.]+'
        /* constantes literales contienen una serie de variados signos � simbolos */
	yylval.nodo = nuevonodo();
	yylval.nodo->tipo = constante_literal; 
	yylval.nodo->subnodos = 0;
	yylval.nodo->num  = instala(contador++);     //yylval.num  = instala(contador++)
if (depurar)
        printf("constante literal: %s    indice %4.0f  en linea : %i \n", yytext, yylval.nodo->num, linenumber);
	return LITERAL; 
	}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
//line 181 "tokens.l"
{ 
        /* constantes literales con commillas */
	yylval.nodo = nuevonodo();
	yylval.nodo->tipo = constante_literal; 
	yylval.nodo->subnodos = 0;
	yylval.nodo->num  = instala(contador++);     //yylval.num  = instala(contador++)
if (depurar)
        printf("constante literal: %s    indice %4.0f  en linea : %i \n", yytext, yylval.nodo->num, linenumber);
	return STRING; 
	}
	YY_BREAK
case 72:
YY_RULE_SETUP
//line 192 "tokens.l"
{ double numdbl = 0;
	yylval.nodo  = nuevonodo();
	yylval.nodo->tipo = un_numero;
	yylval.nodo->subnodos = 0;
	/* tofloat */
	sscanf( yytext, "%lf", &numdbl);
	yylval.nodo->num  = numdbl;     //yylval.num  = atoi(yytext)
	return NUMBER; 
	}
	YY_BREAK
case 73:
YY_RULE_SETUP
//line 202 "tokens.l"
{
        /* nombres de variables numericas en minusculas */

lineaEjecucion2();
//printf("var num lineaEjecución: %d\n", lineaEjecucion);

	yylval.nodo  = nuevonodo();
	yylval.nodo->tipo = indice_strings;
	yylval.nodo->subnodos = 0;
	yylval.nodo->num  = instalavar(contadorvar++);   //yylval.num  = instalavar(contadorvar++)
                //array_variables[(int)yylval.nodo->num].numero=0;  // esto debe ponerse en un bucle al inicio del programa
                if (!myflag)
                array_variables[(int)yylval.nodo->num].tipo = 'N';   //numero
if (depurar)
	printf("variable numerica: %s    indice %4.0f   en linea : %i \n", yytext, yylval.nodo->num, linenumber );
        yylval.nodo->nrolinea1 = yylval.nodo->nrolinea2 = linenumber;
	return NAME; 
	}
	YY_BREAK
case 74:
YY_RULE_SETUP
//line 222 "tokens.l"
{
        /* nombres de variables ALFANUMERICAS van en mayusculas */
        lineaEjecucion2();
	yylval.nodo  = nuevonodo();
	yylval.nodo->tipo = nombre_de_variable;
	yylval.nodo->subnodos = 0;
	yylval.nodo->num  = instalavar(contadorvar++);   //yylval.num  = instalavar(contadorvar++)
	//strcpy(array_variables[(int)yylval.nodo->num].valor, "(null)");
                array_variables[(int)yylval.nodo->num].tipo = 'S';   //string
if (depurar)
                printf("variable alfanumerica: %s    indice %4.0f   en linea : %i \n", yytext, yylval.nodo->num, linenumber );
	return SNAME; 
	}
	YY_BREAK
case 75:
YY_RULE_SETUP
//line 237 "tokens.l"
{ ; }
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
//line 238 "tokens.l"
{ nextline(); }
	YY_BREAK
case 77:
YY_RULE_SETUP
//line 239 "tokens.l"
{ ; }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
//line 240 "tokens.l"
{ nextline(); }
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
//line 241 "tokens.l"
{  cuentalineas( yytext  ) ; } /* comentarios multilinea  */
	YY_BREAK
case 80:
YY_RULE_SETUP
//line 243 "tokens.l"
{ 
               yyerror2("caracter ilegal", yytext[0]); 
}
	YY_BREAK
case 81:
YY_RULE_SETUP
//line 246 "tokens.l"
ECHO;
	YY_BREAK
//line 1601 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 500 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 500 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 499);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

//line 246 "tokens.l"

#ifndef yywrap
yywrap() { return 1; }
#endif

//int * nuevoValorEnteros(int cantidad) {
  //  int * vector = malloc(sizeof(int)*cantidad);
   // return vector;
//}

 ast * nuevonodo()  {
 ast * p;
p = (ast *) malloc(sizeof(struct ast));

extern long memoria;
memoria += sizeof(struct ast);
nodos++;
if (depurar)
printf("nuevo nodo: %ld      %p\n", memoria,  p);   //printf("%p", (void *)&var);
//printf ("A pointer is %ld bytes\n", sizeof (p));

p->num = 0;
p->tipo = 9999;
 
p->subnodos = 0;
p->nodo1 = NULL;
p->nodo2 = NULL;
p->nodo3 = NULL;
p->nodo4 = NULL;
p->nodo5 = NULL;


return p;

}

void  cuentalineas( char * texto ) {
int i = 0;
for (i=0; i < strlen(texto); i++ ) {
        if  ( texto[i] == '\n' || texto [i] == '\r') linenumber++;
    }
}

